config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
    has_many :reviews, dependent: :destroy
    validates :name, presence: true
    validates :phone_number, presence: true
    validates :address, presence: true
    validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }, numericality: { only_integer: true }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where(restaurant_id: params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurant_path(@restaurant)
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
before_action :set_restaurant

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save

    redirect_to restaurant_path(params[:restaurant_id])
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
  <%= simple_form_for(@restaurant) do |f| %>
    <% if @restaurant.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :Name %>
    <%= f.text_field :name %>
    <%= f.label :Address %>
    <%= f.text_field :address %>
    <%= f.label :Phone_number %>
    <%= f.text_field :phone_number %>
    <%= f.label :Category %>
    <%= f.text_field :category %>
    <%= f.submit %>

  <% end %>

app/views/restaurants/create.html.erb
<h1>Restaurants#create</h1>
<p>Find me in app/views/restaurants/create.html.erb</p>

app/views/restaurants/index.html.erb
<h1>Restaurants#index</h1>
<p>Find me in app/views/restaurants/index.html.erb</p>


<% @restaurants.each do |restaurant| %>
  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
  <p><%= restaurant.address %></p>
  <p><%= restaurant.phone_number %></p>
  <p><%= restaurant.category %></p>
<% end %>


<%= link_to "+ Add a New Restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>Adding a New Restaurant#new</h1>
<p>Find me in app/views/restaurants/new.html.erb</p>

<%= render 'form', task: @restaurants %>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>

<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.phone_number %></p>
<p><%= @restaurant.category %></p>
<p><% @reviews.each do |r|%></p>
    <p>Review: <%= r.content %></p>
    <p>Rating: <%= r.rating %></p>
<p><% end %></p>

<%= link_to "+ Add a Review For This Restaurant", new_restaurant_review_path(@restaurant) %>

<br>

<%= link_to "<= Back to All Restaurants List", restaurants_path %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

<h1>Thank you for your review!</h1>

<%= link_to restaurant_reviews_path(@restaurant) %>

app/views/reviews/new.html.erb
<h1>New Review#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

<%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating %>
    <%= f.submit "add a review", class: "btn btn-primary" %>
  <% end %>

 